# Generated by Django 5.2.8 on 2025-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_createdat_user_createdby_user_isdeleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createdAt",
            field=models.BigIntegerField(default=1764589971683),
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.BigIntegerField(default=1764589971683),
        ),
    ]
