# Generated by Django 5.2.8 on 2025-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_createdat_alter_user_updatedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="createdAt",
            field=models.BigIntegerField(default=1764656167924),
        ),
        migrations.AlterField(
            model_name="user",
            name="updatedAt",
            field=models.BigIntegerField(default=1764656167924),
        ),
    ]
