# Generated by Django 5.2.8 on 2025-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="createdAt",
            field=models.BigIntegerField(default=1764310484670),
        ),
        migrations.AlterField(
            model_name="task",
            name="updatedAt",
            field=models.BigIntegerField(default=1764310484670),
        ),
    ]
