# Generated by Django 5.2.8 on 2025-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_createdat_alter_task_updatedat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="createdAt",
            field=models.BigIntegerField(default=1764656167925),
        ),
        migrations.AlterField(
            model_name="task",
            name="updatedAt",
            field=models.BigIntegerField(default=1764656167925),
        ),
    ]
