# Generated by Django 5.2.8 on 2025-11-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="createdAt",
            field=models.BigIntegerField(default=1764310484670),
        ),
        migrations.AddField(
            model_name="user",
            name="createdBy",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="isDeleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="updatedAt",
            field=models.BigIntegerField(default=1764310484670),
        ),
        migrations.AddField(
            model_name="user",
            name="updatedBy",
            field=models.CharField(null=True),
        ),
    ]
